### ISSUE TITLE
Hi Could u help us to update the tool, due to the change of GORUC

### ISSUE THREAD

**Issue by FangmingZhou** [abuccts/goruc#1]
Hi, we are very thankful for this USEFUL tool goruc-cli!
But  not long ago, the ITS center have changed the  login mechanism of GORUC, including IP address and more.
It would be VERY GRATEFUL  if you could help us to update the tool !
If u need any infomation about this , please contact me at fangming_zhou@ruc.edu.cn
THANKS AGAIN!

**Comment by abuccts** [comment]
Hi @FangmingZhou, sorry for the late response. Since I haven't accessed the campus network for many years, I have neither time nor test environment to keep this tool update anymore. I will archive this repo but feel free to fork and modify by yourself, you are welcomed to leverage this cli or other similar gateway connection tools. You may also request an official one from IT service center.
